/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Rbac } from "./Rbac";
export * as factories from "./factories";
export { Rbac__factory } from "./factories/Rbac__factory";
